layerIds:
    _BASE: 0
    _NAV: 1
    _NUM: 2
    _SYM: 3
    _FUN: 4
    _MED: 5
    _SYS: 6
    _MBO: 7
keyLayerToggles:
    CKC_BSPC: 1
    CKC_SPC: 2
    CKC_TAB: 3
    CKC_BKTAB: 4
keyLabels:
    # Custom tap-dance keys (CKC_*)
    CKC_BSPC: "%%nf-md-brain %%nf-md-backspace"
    CKC_SPC: "%%nf-md-keyboard_space"
    CKC_TAB: "%%nf-md-keyboard_tab"
    CKC_BKTAB: "%%nf-md-keyboard_tab_reverse"
    CKC_SMSFT: "%%nf-md-brain %%nf-md-apple_keyboard_shift"

    # Custom macro keys (MKC_*)
    MKC_BKTAB: "%%nf-md-keyboard_tab_reverse"
    MKC_APPWIN: "%%nf-md-apple_keyboard_control %%nf-md-apple_keyboard_command %%nf-fa-arrow_down"
    MKC_ALLWIN: "%%nf-md-apple_keyboard_control %%nf-md-apple_keyboard_command %%nf-fa-arrow_up"
    MKC_DKTN: "%%nf-md-apple_keyboard_control %%nf-md-apple_keyboard_command %%nf-fa-arrow_right"
    MKC_DKTP: "%%nf-md-apple_keyboard_control %%nf-md-apple_keyboard_command %%nf-fa-arrow_left"
    MKC_SHDKT: "%%nf-md-monitor"
    MKC_SHNOT: "%%nf-md-bell"
    MKC_SPAPP: "%%nf-md-magnify %%nf-md-application"
    MKC_SPFND: "%%nf-md-magnify %%nf-md-file_search"
    ML_ALT: "%%nf-md-apple_keyboard_option OPT"

    # Mouse button keys (MB_*)
    MB_SFT: "L%%nf-md-mouse"
    MB_ALT: "R%%nf-md-mouse"
    MB_GUI: "M%%nf-md-mouse"
    MB_CTL: "4%%nf-md-mouse"

    # Svalboard-specific keys (SV_*)
    SV_LDPU: "L %%nf-md-mouse_move_up"
    SV_LDPD: "L %%nf-md-mouse_move_down"
    SV_RDPU: "R %%nf-md-mouse_move_up"
    SV_RDPD: "R %%nf-md-mouse_move_down"
    SV_SOUT: "%%nf-oct-log"
    SV_SNIPER_3: "3%%nf-md-crosshairs"
    SV_SNIPER_5: "5%%nf-md-crosshairs"

secondaryColor: "#70768B"

layers:
    - name: COLEMAK
      baseColor: "#347156"
    - name: Navigation
      baseColor: "#89511C"
    - name: Numbers
      baseColor: "#41687E"
    - name: Symbols
      baseColor: "#8C3B2C"
    - name: Function Keys
      baseColor: "#5F4B7E"
    - name: Multimedia
      baseColor: "#7E6E1E"
    - name: System
      baseColor: "#9C2927"
    - name: Mouse
      baseColor: "#8C3396"
