layerIds:
    _BASE: 0
    _NAV: 1
    _NUM: 2
    _SYM: 3
    _FUN: 4
    _MED: 5
    _SYS: 6
    _MBO: 7

keyLayerToggles:
    CKC_BSPC: 1
    CKC_SPC: 2
    CKC_TAB: 3
    CKC_BKTAB: 4

keyLabels:
    # Custom tap-dance keys (CKC_*)
    CKC_BSPC: "%%nf-md-brain; @@KC_BACKSPACE;"
    CKC_SPC: "@@KC_SPACE;"
    CKC_TAB: "@@KC_TAB;"
    CKC_BKTAB: "%%nf-md-keyboard_tab_reverse;"
    CKC_SMSFT: "%%nf-md-brain; @@KC_LEFT_SHIFT;"

    # Custom macro keys (MKC_*)
    MKC_BKTAB: "@@CKC_BKTAB;"
    MKC_APPWIN: "@@KC_LEFT_CTRL; @@KC_LEFT_GUI; @@KC_DOWN;"
    MKC_DKTN: "@@KC_LEFT_CTRL; @@KC_LEFT_GUI; @@KC_RIGHT;"
    MKC_DKTP: "@@KC_LEFT_CTRL; @@KC_LEFT_GUI; @@KC_LEFT;"
    MKC_SHDKT: "%%nf-md-monitor;"
    MKC_SHNOT: "%%nf-md-bell;"
    MKC_SPFND: "%%nf-md-magnify; %%nf-md-file_search;"
    ML_ALT: "@@KC_LEFT_ALT; OPT"

    # Mouse button keys (MB_*)
    MB_SFT: "@@KC_BTN1;"
    MB_ALT: "@@KC_BTN2;"
    MB_GUI: "@@KC_BTN3;"
    MB_CTL: "@@KC_BTN4;"

    # Svalboard-specific keys (SV_*)
    SV_LDPU: "@@SV_LEFT_DPI_INC;"
    SV_LDPD: "@@SV_LEFT_DPI_DEC;"
    SV_RDPU: "@@SV_RIGHT_DPI_INC;"
    SV_RDPD: "@@SV_RIGHT_DPI_DEC;"
    SV_SOUT: "@@SV_OUTPUT_STATUS;"

secondaryColor: "#70768B"

layers:
    - name: COLEMAK
      baseColor: "#347156"
    - name: Navigation
      baseColor: "#89511C"
    - name: Numbers
      baseColor: "#41687E"
    - name: Symbols
      baseColor: "#8C3B2C"
    - name: Function Keys
      baseColor: "#5F4B7E"
    - name: Multimedia
      baseColor: "#7E6E1E"
    - name: System
      baseColor: "#9C2927"
    - name: Mouse
      baseColor: "#8C3396"
